// <auto-generated />
using System;
using KeywordTag.Database.SQLServer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeywordTag.Database.SQLServer.Migrations
{
    [DbContext(typeof(KeywordTagContext))]
    [Migration("20250116143501_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kt")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KeywordTag.Database.SQLServer.Tables.Checkin", b =>
                {
                    b.Property<Guid>("code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("checkintime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("code_device")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("code_keyword")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("code");

                    b.ToTable("Checkins", "kt");
                });

            modelBuilder.Entity("KeywordTag.Database.SQLServer.Tables.Device", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("code")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("email_pin")
                        .HasColumnType("int");

                    b.Property<string>("list_keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("list_keyword_tagged")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email");

                    b.ToTable("Devices", "kt");
                });

            modelBuilder.Entity("KeywordTag.Database.SQLServer.Tables.Keyword", b =>
                {
                    b.Property<Guid>("code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("confirm")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Keywords", "kt");
                });

            modelBuilder.Entity("KeywordTag.Database.SQLServer.Tables.Message", b =>
                {
                    b.Property<int>("code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("code"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("Messages", "kt");

                    b.HasData(
                        new
                        {
                            code = 1,
                            name = "Message 1"
                        },
                        new
                        {
                            code = 2,
                            name = "Message 2"
                        },
                        new
                        {
                            code = 3,
                            name = "Message 3"
                        });
                });

            modelBuilder.Entity("KeywordTag.Database.SQLServer.Tables.Tag", b =>
                {
                    b.Property<Guid>("code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("code_keyword")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("code_message")
                        .HasColumnType("int");

                    b.Property<DateTime>("tagtime")
                        .HasColumnType("datetime2");

                    b.HasKey("code");

                    b.ToTable("Tags", "kt");
                });

            modelBuilder.Entity("KeywordTag.Database.SQLServer.Views.TopKeywordIdView", b =>
                {
                    b.Property<Guid>("Code")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("TopKeywordIdView", "kt");
                });
#pragma warning restore 612, 618
        }
    }
}
